---
  - name: Install software
    become: True
    apt:
      name:
        - calico-node
        - bird
        - ipset
        - calico-cni-plugin
        - cni-plugins
        - conntrack
      state: present
      update_cache: yes
      cache_valid_time: 1800

  - name: Ensure that bird6 is disabled
    become: True
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    with_items:
      - bird6

  - name: Upload calico environment
    become: True
    template:
      src: calico-env.j2
      dest: /etc/calico/env.sh
      owner: root
      group: root
      mode: 0644
    notify:
      - restart calico-felix
      - restart calico-confd

  - name: Create calico config folders
    become: True
    file:
      path: "/etc/calico/{{ item }}"
      owner: root
      group: root
      mode: 0750
      state: directory
    with_items:
      - confd
      - confd/conf.d
      - confd/templates

  - name: Upload calico templates
    become: True
    copy:
      src: "files/confd/{{ item }}"
      dest: "/etc/calico/confd/{{ item }}"
      owner: root
      group: root
      mode: 0640
    with_items:
    # There are more files, but we only upload those we need *right now*
      - templates/bird.cfg.template
      - templates/bird_aggr.cfg.template
      - templates/bird_ipam.cfg.template
    notify: restart calico-confd

  - name: Lookup bird user
    become: True
    getent:
      database: passwd
      key: bird
      split: ':'

  - name: Upload calico templates templates
    become: True
    template:
      src: "{{ item }}.j2"
      dest: "/etc/calico/confd/conf.d/{{ item }}"
      owner: root
      group: root
      mode: 0640
    vars:
      calico_node_bird_user: "{{ getent_passwd.bird }}"
    with_items:
    # There are more files, but we only upload those we need *right now*
      - bird.toml
      - bird_aggr.toml
      - bird_ipam.toml
    notify: restart calico-confd

  - name: Add calico-felix service
    become: True
    template:
      src: calico-felix.service.j2
      dest: /etc/systemd/system/calico-felix.service
      owner: root
      group: root
      mode: 0644
    notify: restart calico-felix

  - name: Add calico-confd service
    become: True
    template:
      src: calico-confd.service.j2
      dest: /etc/systemd/system/calico-confd.service
      owner: root
      group: root
      mode: 0644
    notify: restart calico-confd

  - name: Ensure cni config dir exists
    become: True
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      mode: 0750
    with_items:
      - /etc/cni
      - /etc/cni/net.d

  - name: Configure calico cni plugin
    become: True
    template:
      src: calico-cni.json.j2
      dest: /etc/cni/net.d/calico-ipam.json
      owner: root
      group: root
      mode: 0644
    notify: restart kubelet

  - name: Configure kernel parameters
    become: True
    template:
      src: sysctl.conf.j2
      dest: /etc/sysctl.d/80-calico-node.conf
      owner: root
      group: root
      mode: 0644
    notify: restart sysctl

  - name: Create bird drop-in directory
    become: True
    when: calico_node_default_route_via_bgp
    file:
      path: /etc/systemd/system/bird.service.d
      owner: root
      group: root
      mode: 0755
      state: directory

  - name: Add 'remote-default-route' dropin to bird
    become: True
    when: calico_node_default_route_via_bgp
    template:
      src: bird-dropin.j2
      dest: /etc/systemd/system/bird.service.d/50-delete-default-route.conf
      owner: root
      group: root
      mode: 0644
    notify: reload systemd

  - name: Add the apiserver-connectivity service
    become: True
    template:
      src: "apiserver-connectivity.{{ item }}.j2"
      dest: "/etc/systemd/system/apiserver-connectivity.{{ item }}"
      owner: root
      group: root
      mode: 0644
    notify: enable connectivity timer
    with_items:
      - service
      - timer

  - name: Add the bird stopping service
    become: True
    template:
      src: "stop-bird.service.j2"
      dest: "/etc/systemd/system/stop-bird.service"
      owner: root
      group: root
      mode: 0644
    notify: enable connectivity timer

  - name: Flush handlers
    meta: flush_handlers
