[template]
src = "bird.cfg.template"
dest = "/etc/bird/bird.conf"
prefix = "/calico/bgp/v1"
keys = [
    "/host",
    "/global",
]
check_cmd = "bird -p -c {{.src}}"
reload_cmd = "systemctl restart bird || true"
