[template]
src = "bird_ipam.cfg.template"
dest = "/etc/bird/bird_ipam.cfg"
prefix = "/calico"
keys = [
    "/v1/ipam/v4/pool",
    "/bgp/v1/host//NODENAME",
    "/staticroutes",
    "/rejectcidrs",
]
reload_cmd = "systemctl restart bird || true"
