[template]
src = "bird_aggr.cfg.template"
dest = "/etc/bird/bird_aggr.cfg"
keys = [
    "/calico/ipam/v2/host//NODENAME/ipv4/block",
    "/calico/staticroutes",
]
reload_cmd = "systemctl restart bird || true"
