---
  - name: restart calico-felix
    become: True
    systemd:
      name: calico-felix
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: restart calico-confd
    become: True
    systemd:
      name: calico-confd
      state: restarted
      enabled: yes
      daemon_reload: yes

  - name: restart kubelet
    become: True
    service:
      name: kubelet
      state: restarted
    failed_when: False
    # The node might not _have_ a kubelet (yet). So don't care about failure...

  - name: restart sysctl
    become: True
    service:
      name: systemd-sysctl
      state: restarted

  - name: reload systemd
    become: True
    systemd:
      daemon_reload: yes

  - name: enable connectivity timer
    become: True
    systemd:
      name: apiserver-connectivity.timer
      daemon_reload: yes
      enabled: yes
      state: started
